version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - carmeet-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root  # กำหนดชื่อผู้ใช้สำหรับการเข้าถึง Mongo Express บนหน้าเว็บ
      ME_CONFIG_BASICAUTH_PASSWORD: example # กำหนดรหัสผ่านสำหรับการเข้าถึง Mongo Express บนหน้าเว็บ
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on: # คำสั่งใช้กำหนดลำดับการเริ่มต้นของบริการ ว่า บริการไหนต้องเริ่มก่อน
      - mongo
    networks: # ใช้กำหนดเครือข่ายที่บริการนี้จะเชื่อมต่อ
      - carmeet-network

networks:
  carmeet-network:
    driver: bridge
